version: '3.8'

services:
  astro-app:
    image: menaheero/coupons:prod
    container_name: Coupons
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4322
    ports:
      - "4322:4322"
    restart: always
    networks:
      - astro-net

networks:
  astro-net:
    driver: bridge
