name: Build
on:
  push:
    branches:
      - main
      - stable

jobs:
  production-build:
    name: Production Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USER --password-stdin

      - name: Production Build Script
        run: |
          docker build -t menaheero/coupons:prod .
          docker push docker.io/menaheero/coupons:prod

  production-deploy:
    name: Production Deploy
    needs: production-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run SSH Commands for Deployment
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /www/astro/copy
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker system prune -af --volumes
          EOF
