name: Build
on:
  push:
    branches:
      - main
      - stable

jobs:
  production-build:
    name: Production Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USER --password-stdin

      - name: Production Build Script
        run: |
          docker build -t menaheero/coupons:prod .
          docker push docker.io/menaheero/coupons:prod

  production-deploy:
    name: Production Deploy
    needs: production-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run SSH Commands for Deployment via Password
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /www/CashCopy
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker system prune -af --volumes
          EOF
