name: Build
on:
  push:
    branches:
      - main
      - stable

jobs:

  production-build:
    name: Production Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Docker Login

        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USER --password-stdin

      - name: Production Build Script
        run: |
          docker build  -t menaheero/coupons:prod .
          docker push  docker.io/menaheero/coupons:prod
  production-deploy:
    name: Production Deploy
    needs: production-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Server SSH Access
        uses: garygrossgarten/github-action-ssh@release

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ""
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          command: |
            cd /www/astro/copy
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker system prune -af --volumes
